name: CI Build

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Test with Jest
      run: npm run test
    - name: Build with ncc
      run: npm run build
